Word Embedding Techniques using Embedding Layer in Keras

https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [2]:
### Libraries USed Tensorflow> 2.0  and keras
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
#sentences
#for better embidding all sentences should have same words
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
#use pad_sequences to make same size

In [7]:
#vocabluary size
voc_size = 10000

One hot Representation

In [8]:
onehot_rep = [one_hot(words,voc_size)for words in sent]
onehot_rep
#all this number will be < 10000

[[3239, 7173, 6078, 8229],
 [3239, 7173, 6078, 8521],
 [3239, 1316, 6078, 714],
 [3465, 495, 2670, 7889, 2873],
 [3465, 495, 2670, 7889, 5839],
 [4434, 3239, 8143, 6078, 5128],
 [576, 1507, 7600, 7889]]

Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
 sent_length = 8
 embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
 embedded_docs

array([[   0,    0,    0,    0, 3239, 7173, 6078, 8229],
       [   0,    0,    0,    0, 3239, 7173, 6078, 8521],
       [   0,    0,    0,    0, 3239, 1316, 6078,  714],
       [   0,    0,    0, 3465,  495, 2670, 7889, 2873],
       [   0,    0,    0, 3465,  495, 2670, 7889, 5839],
       [   0,    0,    0, 4434, 3239, 8143, 6078, 5128],
       [   0,    0,    0,    0,  576, 1507, 7600, 7889]], dtype=int32)

In [14]:
#now choose features 
dimensions = 10
model= Sequential()
model.add(Embedding(voc_size,dimensions,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

array([[[-0.0468399 ,  0.04498937,  0.0317628 ,  0.04500702,
          0.00824793,  0.02456914,  0.04659373, -0.04015443,
         -0.02954701,  0.02147045],
        [-0.0468399 ,  0.04498937,  0.0317628 ,  0.04500702,
          0.00824793,  0.02456914,  0.04659373, -0.04015443,
         -0.02954701,  0.02147045],
        [-0.0468399 ,  0.04498937,  0.0317628 ,  0.04500702,
          0.00824793,  0.02456914,  0.04659373, -0.04015443,
         -0.02954701,  0.02147045],
        [-0.0468399 ,  0.04498937,  0.0317628 ,  0.04500702,
          0.00824793,  0.02456914,  0.04659373, -0.04015443,
         -0.02954701,  0.02147045],
        [-0.02003186, -0.02769424, -0.03058237,  0.00469889,
         -0.02999213, -0.01467596, -0.0052653 ,  0.0447293 ,
         -0.01760715,  0.04670611],
        [ 0.03658209, -0.00284778,  0.02654124,  0.02709684,
          0.00368803,  0.03486652, -0.03642008,  0.0384005 ,
          0.00796678,  0.04871925],
        [-0.04638017, -0.02730316,  0.01137248, -0.0

In [18]:
print(embedded_docs[0])
print(model.predict(embedded_docs[0]))

[   0    0    0    0 3239 7173 6078 8229]
[[[-0.0468399   0.04498937  0.0317628   0.04500702  0.00824793
    0.02456914  0.04659373 -0.04015443 -0.02954701  0.02147045]]

 [[-0.0468399   0.04498937  0.0317628   0.04500702  0.00824793
    0.02456914  0.04659373 -0.04015443 -0.02954701  0.02147045]]

 [[-0.0468399   0.04498937  0.0317628   0.04500702  0.00824793
    0.02456914  0.04659373 -0.04015443 -0.02954701  0.02147045]]

 [[-0.0468399   0.04498937  0.0317628   0.04500702  0.00824793
    0.02456914  0.04659373 -0.04015443 -0.02954701  0.02147045]]

 [[-0.02003186 -0.02769424 -0.03058237  0.00469889 -0.02999213
   -0.01467596 -0.0052653   0.0447293  -0.01760715  0.04670611]]

 [[ 0.03658209 -0.00284778  0.02654124  0.02709684  0.00368803
    0.03486652 -0.03642008  0.0384005   0.00796678  0.04871925]]

 [[-0.04638017 -0.02730316  0.01137248 -0.02246265  0.04672149
   -0.0044399  -0.0106226   0.0129511   0.02647027 -0.0221233 ]]

 [[ 0.01365925  0.03323753 -0.04873263 -0.00517393  0.0